#Port Define
server.port : 8080

#App name
spring.application.name : API-GATEWAY

#Api Routes
spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /auth/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates :
            - Path= /user/**
          filters:
            - JwtAuthenticationFilter

        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path= /order/**
          filters:
            - JwtAuthenticationFilter



#Eureka Client Config
eureka.instance.prefer-ip-address   : true
eureka.client.fetch-registry        : true
eureka.client.register-with-eureka  : true
eureka.client.service-url.defaultZone : http://localhost:8761/eureka
